server:
  port: 13200
spring:
  application:
    name: cloud-service-admin-statistics
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.150:8848
    sentinel:
      transport:
        dashboard: 192.168.30.150:8080
  datasource:
    #    url: jdbc:mysql://192.168.30.150:3306/spring-boot-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://192.168.30.150:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: xinbo123321
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
    #    schema:
    #      - "classpath:db/schema.sql"
    #    data:
    #      - "classpath:db/data.sql"
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
logging:
  level:
    com.xinbo: debug
  file:
    max-size: 5MB
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/common/*.xml,classpath:mappers/sport/*.xml,classpath:mappers/lottery/*.xml,classpath:mappers/statistics/*.xml
  type-aliases-package: com.xinbo.cloud.common.domain
mapper:
  mappers:
    - tk.mybatis.mapper.MyMapper
  not-empty: true
  style: camelhump
  wrap-keyword: "`{0}`"
  safe-delete: true
  safe-update: true
  identity: MYSQL
pagehelper:
  auto-dialect: true
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
dubbo:
  scan:
    base-packages: com.xinbo.cloud.service.admin.statistics
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
    generic: false
  registry:
    address: nacos://192.168.30.150:8848
    check: false
rocketmq:
  name-server: 192.168.30.150:9876
  producer-group: statistics_rocketmq_consumer_group
  producer-timeout: 300000
web:
  #请求头
  header-key: Authorization
  #前缀
  prefix: Bearer
  #放行url多个用逗号隔开(如：/a,/b,/c)
  ignore-url: /swagger-resources/**,/webjars/**,/v2/**,/swagger-ui.html/**,/configuration/**
