FROM openjdk:8
VOLUME /tmp
ADD skywalking-7.0.0.tar.gz /skywalking
ADD cloud-service-admin-statistics.jar app.jar
EXPOSE 13200
ENTRYPOINT ["java","-Dskywalking.agent.service_name=cloud-service-admin-statistics", "-Dskywalking.collector.backend_service=192.168.30.88:11800", "-javaagent:/skywalking/skywalking-agent.jar", "-Dorg.apache.skywalking.apm.dependencies.io.netty.noUnsafe=true", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=prod", "-jar", "/app.jar"]
